# Generated by Django 4.1.3 on 2022-12-05 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('presente', models.BooleanField(default=True)),
                ('classe', models.CharField(choices=[('Ações', 'Ações_BR'), ('FIIs', 'Fundos Imobiliários'), ('Stocks', 'Stocks'), ('REITs', 'Reits americanos'), ('cryptos', 'Criptoativos'), ('ETF-BR', 'ETF BR'), ('ETF-US', 'ETF US'), ('Caixa', 'Caixa')], default='Caixa', max_length=10)),
                ('nome', models.CharField(max_length=10)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('saldo', models.FloatField(blank=True, null=True)),
                ('pm', models.FloatField(blank=True, null=True)),
                ('valor_atual', models.FloatField(blank=True, null=True)),
                ('lucro_preju', models.FloatField(blank=True, null=True)),
                ('pminpago', models.FloatField(blank=True, null=True)),
                ('pmaxpago', models.FloatField(blank=True, null=True)),
                ('percentual_classe', models.CharField(blank=True, max_length=10, null=True)),
                ('percentual_lucro', models.CharField(blank=True, max_length=10, null=True)),
                ('saldo_USD', models.FloatField(blank=True, null=True)),
                ('pm_USD', models.FloatField(blank=True, null=True)),
                ('valor_atual_USD', models.FloatField(blank=True, null=True)),
                ('percentual_patrimonio', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('presente', models.BooleanField(default=True)),
                ('valor', models.FloatField(blank=True, default=0, null=True)),
                ('valor_acoes', models.FloatField(blank=True, default=0, null=True)),
                ('percentual_acoes', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('valor_fiis', models.FloatField(blank=True, default=0, null=True)),
                ('percentual_fiis', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('valor_stocks', models.FloatField(blank=True, default=0, null=True)),
                ('percentual_stocks', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('valor_reits', models.FloatField(blank=True, default=0, null=True)),
                ('percentual_reits', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('valor_cryptos', models.FloatField(blank=True, default=0, null=True)),
                ('percentual_cryptos', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('valor_etf_br', models.FloatField(blank=True, default=0, null=True)),
                ('percentual_etfs_br', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('valor_etfs_us', models.FloatField(blank=True, default=0, null=True)),
                ('percentual_etfs_us', models.CharField(blank=True, default='', max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('presente', models.BooleanField(default=True)),
                ('ativo_vendido', models.CharField(max_length=10)),
                ('qtd_vendido', models.IntegerField()),
                ('ativo_comprado', models.CharField(max_length=10)),
                ('qtd_comprado', models.IntegerField()),
                ('unid_comprada', models.FloatField()),
                ('unid_vendido', models.FloatField()),
                ('unid_comprado_USD', models.FloatField()),
                ('unid_vendido_USD', models.FloatField()),
                ('taxas', models.FloatField()),
                ('Cambio_USD', models.FloatField()),
                ('PM_Ativo_Comprado', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
