# Generated by Django 4.1.3 on 2022-12-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='taxas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
