# Generated by Django 4.1.3 on 2022-12-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0002_alter_registro_taxas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='unid_comprado_USD',
            new_name='unid_comprada_USD',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='unid_vendido',
            new_name='unid_vendida',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='unid_vendido_USD',
            new_name='unid_vendida_USD',
        ),
    ]
