# Generated by Django 4.1.3 on 2022-12-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0003_rename_unid_comprado_usd_registro_unid_comprada_usd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='ativo_vendido',
            new_name='ativo_utilizado',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='qtd_comprado',
            new_name='total_entrada',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='qtd_vendido',
            new_name='total_saida',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='unid_comprada',
            new_name='valor_unit_entrada',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='unid_vendida',
            new_name='valor_unit_saida',
        ),
    ]
