# Generated by Django 4.1.3 on 2022-12-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0004_rename_ativo_vendido_registro_ativo_utilizado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='Cambio_USD',
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='dividendos_reinvestidos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='origem_dividendos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='PM_Ativo_Comprado',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='cambio_USD',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
